packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@eslint/compat': ^1.2.9
  '@eslint/js': ^9.27.0
  '@playwright/test': ^1.52.0
  '@sentry/sveltekit': ^9.19.0
  '@sveltejs/adapter-vercel': ^5.7.2
  '@sveltejs/kit': ^2.21.0
  '@sveltejs/vite-plugin-svelte': ^5.0.3
  '@tailwindcss/vite': ^4.1.7
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/svelte': ^5.2.7
  '@types/eslint': ^9.6.1
  '@types/eslint-config-prettier': ^6.11.3
  '@types/jsdom': ^21.1.7
  '@types/node': ^22.15.18
  'dotenv': ^16.5.0
  'dotenv-expand': ^12.0.2
  'eslint': ^9.27.0
  'eslint-config-prettier': ^10.1.5
  'eslint-plugin-perfectionist': ^4.13.0
  'eslint-plugin-svelte': ^3.8.0
  'globals': ^16.1.0
  'jsdom': ^26.1.0
  'prettier': ^3.5.3
  'prettier-plugin-organize-attributes': ^1.0.0
  'prettier-plugin-svelte': ^3.4.0
  'prettier-plugin-tailwindcss': ^0.6.11
  'svelte': ^5.30.1
  'svelte-check': ^4.2.1
  'tailwindcss': ^4.1.7
  'tsup': ^8.5.0
  'turbo': ^2.5.3
  'typescript': ^5.8.3
  'typescript-eslint': ^8.32.1
  'vite': ^6.3.5
  'vitest': ^3.1.3
